config {
    type: "table",
    schema: "JIRA_REWORK",
    name: "03_rework"
}

SELECT

 

  --col E
  CASE
    WHEN `Type de ticket` IS NULL THEN NULL
    WHEN `Nom de lépopée` IS NULL THEN 'Épopée à définir'
    ELSE CONCAT('https://jira.systeme-u.com/browse/', COALESCE(`Date résolution`, ''), REPLACE(`Nom de lépopée`, "'", ""))
  END AS `Nom de lépopée`,

  

 
 
FROM
  `tec-pocappscript-r-6lbj.JIRA_REWORK.02_rework` AS data_table













  
